# Generated by Django 3.1.1 on 2020-09-19 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cadastro_acesso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(help_text='Por favor insira um CPF válido, somente números.', max_length=11)),
                ('nome', models.CharField(max_length=30)),
                ('senha', models.CharField(max_length=8)),
                ('celular', models.CharField(help_text='Por favor insira somente números. Ex.51999999999', max_length=11)),
                ('obs', models.TextField(blank=True, max_length=150, null=True)),
                ('data_ini', models.DateTimeField()),
                ('data_fim', models.DateTimeField()),
                ('ativo', models.BooleanField(default=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_cadastros')),
            ],
        ),
    ]
