# Generated by Django 3.1.1 on 2020-09-20 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acessos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro_acesso',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
