# Generated by Django 3.1.1 on 2020-09-20 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acessos', '0002_cadastro_acesso_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro_acesso',
            name='cpf',
            field=models.CharField(help_text='Por favor insira um CPF válido, somente números.', max_length=11, unique=True),
        ),
    ]
