# Generated by Django 3.1.1 on 2020-09-25 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acessos', '0003_auto_20200920_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='config_comunicacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=50, null=True)),
                ('senha', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('email_copia', models.EmailField(max_length=254)),
                ('smtp', models.CharField(blank=True, max_length=50, null=True)),
                ('autenticacao', models.BooleanField(default=True)),
                ('ssl', models.BooleanField(default=True)),
                ('obs', models.TextField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='config_geral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cor_login', models.CharField(max_length=10)),
                ('cor_main', models.CharField(max_length=10)),
                ('cor_menu', models.CharField(max_length=10)),
                ('obs', models.TextField(blank=True, max_length=150, null=True)),
                ('foto_bg', models.ImageField(blank=True, null=True, upload_to='fotos_cadastros')),
                ('foto_logo', models.ImageField(blank=True, null=True, upload_to='fotos_cadastros')),
            ],
        ),
    ]
