# Generated by Django 3.1.1 on 2020-09-25 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acessos', '0004_config_comunicacao_config_geral'),
    ]

    operations = [
        migrations.AddField(
            model_name='config_geral',
            name='nome_empresa',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='config_geral',
            name='cor_login',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='config_geral',
            name='cor_main',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='config_geral',
            name='cor_menu',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
